import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/components/providers';
import { isClerkConfigured } from '@/lib/auth-helpers';

export const metadata: Metadata = {
  title: 'CodeMentor AI — Personal Coding Interview DSA Study Coach',
  description: 'Connect your LeetCode profile, identify weaknesses, and follow a personalized study plan generated by AI.',
  keywords: ['leetcode', 'dsa', 'interview preparation', 'software engineering', 'study coach', 'ai recruiter']
};

export const viewport = {
  width: 'device-width',
  initialScale: 1
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = <Providers>{children}</Providers>;

  // If Clerk auth keys are set, wrap in ClerkProvider, otherwise boot in mock mode
  if (isClerkConfigured) {
    // We import ClerkProvider only when active to save weight
    const { ClerkProvider } = require('@clerk/nextjs');
    return (
      <ClerkProvider>
        <html lang="en" className="h-full scroll-smooth">
          <body className="min-h-full flex flex-col">{content}</body>
        </html>
      </ClerkProvider>
    );
  }

  return (
    <html lang="en" className="h-full scroll-smooth">
      <body className="min-h-full flex flex-col">{content}</body>
    </html>
  );
}
